# ARG NODE_VERSION=20.14.0
ARG NODE_VERSION=22.13.1

# Create build stage
FROM node:${NODE_VERSION}-slim AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json files to the working directory
COPY ./package.json /app/
COPY ./package-lock.json /app/

# Install dependencies
RUN npm ci

# Copy the rest of the application files to the working directory
COPY . ./

# Build the application
RUN npm run build-staging

# Create a new stage for the production image
FROM node:${NODE_VERSION}-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the output from the build stage to the working directory
COPY --from=build /app/.output ./

# Define environment variables
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=4000 
ENV NODE_ENV=production

# Expose the port the application will run on
EXPOSE 4000

# Start the application
CMD ["node", "/app/server/index.mjs"]